[Hotkeys]
; OpenXR Runtime Switcher
steamxr=Ctrl+Shift+Alt+F7
oculus_openxr=Ctrl+Shift+Alt+F8
pimax=Ctrl+Shift+Alt+F9
mixedreality=Ctrl+Shift+Alt+F10
varjo=Ctrl+Shift+Alt+F11
virtualdesktop=Ctrl+Shift+Alt+F12